# Generated by Django 4.2.6 on 2023-10-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='none', max_length=254, unique=True),
        ),
    ]
