# Generated by Django 4.2.6 on 2023-11-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(db_column='assettype_name', on_delete=django.db.models.deletion.PROTECT, to='inventory.assettype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(db_column='department_name', on_delete=django.db.models.deletion.PROTECT, to='inventory.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase',
            field=models.ForeignKey(db_column='purchase_invoice_no', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.purchase'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(db_column='room_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.room'),
        ),
    ]
