# Generated by Django 4.2.6 on 2023-10-26 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_asset_target_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='specs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
