# Generated by Django 4.2.6 on 2023-11-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_asset_target_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasset',
            name='asset',
            field=models.ForeignKey(db_column='asset_serial_no', on_delete=django.db.models.deletion.PROTECT, to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='subasset',
            name='purchase',
            field=models.ForeignKey(db_column='purchase_invoice_no', on_delete=django.db.models.deletion.PROTECT, to='inventory.purchase'),
        ),
    ]
