# Generated by Django 4.2.6 on 2023-11-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_subasset_asset_alter_subasset_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(db_column='vendor name', on_delete=django.db.models.deletion.PROTECT, to='inventory.vendor'),
        ),
    ]
